import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics documentation
  docsSidebar: [
    {
      type: 'category',
      label: 'Part I: Infrastructure',
      items: [
        'part-i-infrastructure/index',
        'part-i-infrastructure/chapter-1-hardware-os-config',
        'part-i-infrastructure/chapter-2-edge-ecosystem',
      ],
    },
    {
      type: 'category',
      label: 'Part II: ROS Nervous System',
      items: [
        'part-ii-ros-nervous-system/index',
        'part-ii-ros-nervous-system/chapter-3-ros2-architecture',
        'part-ii-ros-nervous-system/chapter-4-urdf-kinematics',
      ],
    },
    {
      type: 'category',
      label: 'Part III: Digital Twin',
      items: [
        'part-iii-digital-twin/index',
        'part-iii-digital-twin/chapter-5-physics-gazebo',
        'part-iii-digital-twin/chapter-6-isaac-sim',
      ],
    },
    {
      type: 'category',
      label: 'Part IV: Perception & Navigation',
      items: [
        'part-iv-perception-navigation/index',
        'part-iv-perception-navigation/chapter-7-sensors-vslam',
        'part-iv-perception-navigation/chapter-8-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Part V: VLA Integration',
      items: [
        'part-v-vla-integration/index',
        'part-v-vla-integration/chapter-9-voice-pipeline',
        'part-v-vla-integration/chapter-10-brain-llm',
        'part-v-vla-integration/chapter-11-vla',
      ],
    },
    {
      type: 'category',
      label: 'Part VI: Capstone',
      items: [
        'part-vi-capstone/index',
        'part-vi-capstone/chapter-12-autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
