openapi: 3.0.3
info:
  title: Auth Server API
  description: Better Auth authentication server API for RAG chatbot
  version: 1.0.0
  contact:
    name: Development Team
    email: dev@example.com

servers:
  - url: http://localhost:3001
    description: Local development server
  - url: https://auth.yourdomain.com
    description: Production server

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: User
    description: User profile management
  - name: Session
    description: Session management

paths:
  # Authentication endpoints (Better Auth handlers)
  /api/auth/signup:
    post:
      tags: [Authentication]
      summary: Create new user account
      description: Register a new user with learning preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request (email already exists, validation errors)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error

  /api/auth/signin:
    post:
      tags: [Authentication]
      summary: Authenticate user
      description: Sign in with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: better-auth.session_token=abc123; HttpOnly; Secure; SameSite=Strict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error

  /api/auth/signout:
    post:
      tags: [Authentication]
      summary: Sign out user
      description: Invalidate current session
      responses:
        '200':
          description: Signed out successfully
          headers:
            Set-Cookie:
              schema:
                type: string
                example: better-auth.session_token=; HttpOnly; Secure; SameSite=Strict; Expires=Thu, 01 Jan 1970 00:00:00 GMT
        '401':
          description: Not authenticated
        '500':
          description: Internal server error

  # Session validation
  /api/auth/get-session:
    get:
      tags: [Session]
      summary: Validate session
      description: Validate current session token and return user data
      responses:
        '200':
          description: Session valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error

  # User profile endpoints
  /api/user/me:
    get:
      tags: [User]
      summary: Get current user profile
      description: Retrieve authenticated user's profile including learning preferences
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error

    put:
      tags: [User]
      summary: Update user profile
      description: Update user's learning preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
        '500':
          description: Internal server error

components:
  schemas:
    # Request schemas
    SignupRequest:
      type: object
      required: [email, password, name]
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: securePassword123
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: John Doe
        educationLevel:
          type: string
          enum: [High School, Undergraduate, Graduate, Professional]
          example: Undergraduate
        programmingExperience:
          type: string
          enum: [No Experience, Beginner, Intermediate, Advanced]
          example: Beginner
        softwareBackground:
          type: string
          example: "Some Python and web development"
        hardwareBackground:
          type: string
          example: "Basic electronics and Arduino"
        roboticsBackground:
          type: string
          enum: [No Experience, Hobbyist, Academic, Professional]
          example: Hobbyist

    SigninRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: securePassword123

    UpdateProfileRequest:
      type: object
      properties:
        educationLevel:
          type: string
          enum: [High School, Undergraduate, Graduate, Professional]
          example: Graduate
        programmingExperience:
          type: string
          enum: [No Experience, Beginner, Intermediate, Advanced]
          example: Intermediate
        softwareBackground:
          type: string
          example: "Professional Python developer"
        hardwareBackground:
          type: string
          example: "Advanced electronics and embedded systems"
        roboticsBackground:
          type: string
          enum: [No Experience, Hobbyist, Academic, Professional]
          example: Academic

    # Response schemas
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: John Doe
        educationLevel:
          type: string
          enum: [High School, Undergraduate, Graduate, Professional]
          example: Undergraduate
        programmingExperience:
          type: string
          enum: [No Experience, Beginner, Intermediate, Advanced]
          example: Beginner
        softwareBackground:
          type: string
          example: "Some Python and web development"
        hardwareBackground:
          type: string
          example: "Basic electronics and Arduino"
        roboticsBackground:
          type: string
          enum: [No Experience, Hobbyist, Academic, Professional]
          example: Hobbyist
        createdAt:
          type: string
          format: date-time
          example: "2025-12-13T10:30:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid credentials"
        message:
          type: string
          example: "The email or password you entered is incorrect"
        code:
          type: string
          example: "INVALID_CREDENTIALS"
        details:
          type: object
          additionalProperties: true

  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: better-auth.session_token
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - sessionCookie: []
  - bearerAuth: []