"""
Base SQLAlchemy models for Better Auth + Neon integration
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

# Base class for SQLAlchemy models
Base = declarative_base()

class User(Base):
    __tablename__ = "user"

    id = Column("id", String, primary_key=True)  # UUID string generated by Better Auth
    email = Column("email", String, unique=True, nullable=False)  # User's email address
    name = Column("name", String, nullable=False)  # User's full name
    education_level = Column("educationLevel", String)  # Education level enum
    programming_experience = Column("programmingExperience", String)  # Programming experience enum
    software_background = Column("softwareBackground", Text)  # Software background description
    hardware_background = Column("hardwareBackground", Text)  # Hardware background description
    robotics_background = Column("roboticsBackground", String)  # Robotics background enum
    created_at = Column("createdAt", DateTime, default=datetime.utcnow)  # Account creation timestamp

class Session(Base):
    __tablename__ = "session"

    id = Column("id", String, primary_key=True)  # UUID string generated by Better Auth
    user_id = Column("userId", String, ForeignKey("user.id", ondelete="CASCADE"), nullable=False)  # References User.id
    token = Column("token", String)  # Session authentication token
    expires_at = Column("expiresAt", DateTime, nullable=False)  # Session expiration timestamp

    # Relationship
    user = relationship("User", back_populates="sessions")

User.sessions = relationship("Session", order_by=Session.expires_at, back_populates="user")

class ChatHistory(Base):
    __tablename__ = "chat_history"

    id = Column("id", Integer, primary_key=True, autoincrement=True)  # Auto-incrementing integer
    user_id = Column("userId", String, ForeignKey("user.id", ondelete="CASCADE"), nullable=False)  # References User.id
    message = Column("message", Text, nullable=False)  # User's question/message to the chatbot
    response = Column("response", Text, nullable=False)  # AI assistant's response
    selected_text = Column("selectedText", Text)  # Text selected from documentation (optional context)
    created_at = Column("createdAt", DateTime, nullable=False, default=datetime.utcnow)  # Message timestamp

    # Relationship
    user = relationship("User", back_populates="chat_histories")

User.chat_histories = relationship("ChatHistory", order_by=ChatHistory.created_at.desc(), back_populates="user")