"""
Session model for Better Auth + Neon integration
"""
from sqlalchemy import Column, String, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

# Base class for SQLAlchemy models
Base = declarative_base()

class Session(Base):
    __tablename__ = "session"

    id = Column("id", String, primary_key=True)  # UUID string generated by Better Auth
    user_id = Column("userId", String, ForeignKey("user.id", ondelete="CASCADE"), nullable=False)  # References User.id with ON DELETE CASCADE
    token = Column("token", String)  # Session authentication token
    expires_at = Column("expiresAt", DateTime, nullable=False)  # Session expiration timestamp

    # Relationship
    user = relationship("User", back_populates="sessions")

    def __repr__(self):
        return f"<Session(id={self.id}, userId={self.user_id}, expiresAt={self.expires_at})>"

    def to_dict(self):
        """Convert session object to dictionary for serialization"""
        return {
            "id": self.id,
            "userId": self.user_id,
            "token": self.token,
            "expiresAt": self.expires_at.isoformat() if self.expires_at else None
        }