"""
User model with learning preferences for Better Auth + Neon integration
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

# Base class for SQLAlchemy models
Base = declarative_base()

class User(Base):
    __tablename__ = "user"

    id = Column("id", String, primary_key=True)  # UUID string generated by Better Auth
    email = Column("email", String, unique=True, nullable=False)  # User's email address
    name = Column("name", String, nullable=False)  # User's full name
    education_level = Column("educationLevel", String)  # Education level enum: "High School", "Undergraduate", "Graduate", "Professional"
    programming_experience = Column("programmingExperience", String)  # Programming experience enum: "No Experience", "Beginner", "Intermediate", "Advanced"

    robotics_background = Column("roboticsBackground", String)  # Robotics background enum: "No Experience", "Hobbyist", "Academic", "Professional"
    created_at = Column("createdAt", DateTime, default=datetime.utcnow)  # Account creation timestamp (default: NOW())

    def __repr__(self):
        return f"<User(id={self.id}, email={self.email}, name={self.name})>"

    def to_dict(self):
        """Convert user object to dictionary for serialization"""
        return {
            "id": self.id,
            "email": self.email,
            "name": self.name,
            "educationLevel": self.education_level,
            "programmingExperience": self.programming_experience,

            "roboticsBackground": self.robotics_background,
            "createdAt": self.created_at.isoformat() if self.created_at else None
        }